export const Routes = {
  HOME: 'Anasayfa',
  GUEST: 'Misafir',
  ADDTRIP: 'Yeni Not Ekle',
  ADDLOCATION: 'Lokasyon Ekle',
  TRIPLIST: 'Lokasyon Notları',
  EDITLIST: 'Edit list',
  TRIPDETAIL: 'Lokasyon Detail',
  INTRO: 'Intro',
  LOGIN: 'Login',
  REGISTER: 'Register',
  SPLASH: 'Splash',
  USER: 'User',
  PROFILE: 'Profile',
};
